### ISSUE TITLE
extract main color of a photo to prevent FOUC

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/jit_image_manipulation#115] opened 2015-12-14 11:05 UTC
it would be a nice enhancement to get the main photo color, to prevent [FOUC]
(https://en.wikipedia.org/wiki/Flash_of_unstyled_content)

<img width="564" alt="screen shot 2015-12-14 at 13 03 03" src="https://cloud.githubusercontent.com/assets/2312755/11779349/12a8fb84-a263-11e5-960c-f82939a85589.png">

**Comment by brendo** [comment] 2015-12-14 12:08
Do you know much about they achieve that effect? I'd be curious to how we support it as this is 'JIT' after all. Potentially this is an enhancement more for an upload field to extract the colour upon save so that it's available via the datasource and can be embedded into the XSLT.

Failing that, maybe the first time JIT runs it extracts this info and saves it in the database. All subsequent requests can used the cached value as the colour may change depending on the crop.

Would be an interesting little project for sure :)

**Comment by michael-e** [comment] 2015-12-14 12:18
If we save anything to the database, we also increase the potential damage ("data pollution") caused by a service/DOS attack. It would as well be much more complicated to drop the JIT cache (which then would be much more than a cache...).

I don't feel that such a feature should be baken into "just-in-time" (JIT) image manipulation. It might be a different extension, maybe.

**Comment by cmnstmntmn** [comment] 2015-12-14 13:47
an ideea
what about appending the hex value to the cached generated image file name.

**to get the img src**
```html 
<img src="{$root}/image/thumbnail{image/@path}/{image/filename}" />
```

**to get the hex value**
```html
 <div style="background-color: <xsl:value-of select="{$root}/image/get-hex{image/@path}/{image/filename}" />"></div>
```

where `get-hex` would be a reserved for this action only

an [example](https://github.com/thephpleague/color-extractor) of how the color is beeing extracted with php

**Comment by cmnstmntmn** [comment] 2015-12-14 14:03
well, a batter solution would be to also include the recipe, becauze different thumbnails would have different 'main color' after cropping

```html
 <div style="background-color: <xsl:value-of select="{$root}/image/landscape{image/@path}/{image/filename}/extract-color" />"></div>

```

**Comment by nitriques** [comment] 2015-12-14 17:14
> it might be a different extension,

I think it should yes. JIT and colors are two separate concerns. I would rather see it being baked in the image upload field rather then the JIT ext.

Warming up your cache may be a good solution to prevent FOUC.

---

I am curious to know why you need this :) It is because images are slow to load ??

**Comment by cmnstmntmn** [comment] 2015-12-14 18:57
yes, slow load is the main concern, 
and, i also agree, that having it as, a different extension is better.

**Comment by nitriques** [comment] 2015-12-14 19:44
> and, i also agree, that having it as, a different extension is better.

Great. So I'll close the issue for the mater being. One could check delegates to add the value in the database, but please think about sending a PR on image upload field if you want !

**Closed by nitriques** 2015-12-14 19:44 UTC
